//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShedule {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SettingsAplication : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsAplication defaultInstance = ((SettingsAplication)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsAplication())));
        
        public static SettingsAplication Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CountWeeksShedule {
            get {
                return ((int)(this["CountWeeksShedule"]));
            }
            set {
                this["CountWeeksShedule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int CountDayEducationalWeek {
            get {
                return ((int)(this["CountDayEducationalWeek"]));
            }
            set {
                this["CountDayEducationalWeek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int CountDaysShedule {
            get {
                return ((int)(this["CountDaysShedule"]));
            }
            set {
                this["CountDaysShedule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int CountLessonsOfDay {
            get {
                return ((int)(this["CountLessonsOfDay"]));
            }
            set {
                this["CountLessonsOfDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int CountEducationalWeekBySem {
            get {
                return ((int)(this["CountEducationalWeekBySem"]));
            }
            set {
                this["CountEducationalWeekBySem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MaxCountLessonsOfWeekDay {
            get {
                return ((int)(this["MaxCountLessonsOfWeekDay"]));
            }
            set {
                this["MaxCountLessonsOfWeekDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MaxCountLessonsOfWeekEnd {
            get {
                return ((int)(this["MaxCountLessonsOfWeekEnd"]));
            }
            set {
                this["MaxCountLessonsOfWeekEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int FirstLessonsOfWeekDay {
            get {
                return ((int)(this["FirstLessonsOfWeekDay"]));
            }
            set {
                this["FirstLessonsOfWeekDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int FirstLessonsOfWeekEnd {
            get {
                return ((int)(this["FirstLessonsOfWeekEnd"]));
            }
            set {
                this["FirstLessonsOfWeekEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int LastLessonsOfWeekDay {
            get {
                return ((int)(this["LastLessonsOfWeekDay"]));
            }
            set {
                this["LastLessonsOfWeekDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int LastLessonsOfWeekEnd {
            get {
                return ((int)(this["LastLessonsOfWeekEnd"]));
            }
            set {
                this["LastLessonsOfWeekEnd"] = value;
            }
        }
    }
}
